#!/bin/sh
set -e

build_all() {
        cd $WORKDIR

        wget -c -t0 http://ftp.iplinux.org/contrib/iplinux-bootstrap/iplinux-bootstrap-LATEST.tar.bz2
        tar xf iplinux-bootstrap-LATEST.tar.bz2
        cd iplinux-bootstrap-*
        ./iplinux-bootstrap --debian-mirror=http://localhost:9999/debian/ openinkpot ../buildroot
        cd ..

        buildroot/enter sh -c 'sudo apt-get install --yes --force-yes oi-build-firmware'

        buildroot/enter sh -c "mkdir -p output/${VERSION}"
        REPORT="output/${VERSION}/report"
        buildroot/enter sh -c "touch ${REPORT}"

        buildroot/enter sh -c "build-fw n516 --variant=azbooka $1" || echo "azbooka failed" >> $REPORT
        buildroot/enter sh -c "build-fw n516 $1" || echo "n516 failed" >> $REPORT
        buildroot/enter sh -c "build-fw v3 $1" || echo "v3 failed" >> $REPORT
        buildroot/enter sh -c "build-fw v3 --mode=live $1" || echo "v3 live failed" >> $REPORT
        buildroot/enter sh -c "build-fw v3 --mode=nfsroot $1" || echo "v3 nfsroot failed" >> $REPORT
        buildroot/enter sh -c "build-fw v3ext $1" || echo "v3ext failed" >> $REPORT

        cd buildroot/build/output/${VERSION}
        md5sum oi-* azbooka* > MD5SUMS
        sha1sum oi-* azbooka* > SHA1SUMS
        cd $WORKDIR
        cp -a buildroot/build/output ~

        cd

        sudo rm -rf "$WORKDIR"
}

WORKDIR=$(mktemp -d  $HOME/buildfw.XXXXXXXX)
VERSION=$(date +%Y%m%d)

build_all $1 > log 2>&1
mv log ~/output/${VERSION}/

