#!/bin/sh
set -e

build_all() {
        cd $WORKDIR

        wget -c -t0 http://ftp.iplinux.org/contrib/iplinux-bootstrap/iplinux-bootstrap-LATEST.tar.bz2
        tar xf iplinux-bootstrap-LATEST.tar.bz2
        cd iplinux-bootstrap-*
        ./iplinux-bootstrap --debian-mirror=http://localhost:9999/debian/ openinkpot ../buildroot
        cd ..

        buildroot/enter sh -c 'sudo apt-get install --yes --force-yes oi-build-firmware'

        buildroot/enter sh -c "build-fw n516 --variant=azbooka $1"
        buildroot/enter sh -c "build-fw n516 $1"
        buildroot/enter sh -c "build-fw v3 $1"  
        buildroot/enter sh -c "build-fw v3 --mode=live $1"
        buildroot/enter sh -c "build-fw v3 --mode=nfsroot $1"
        buildroot/enter sh -c "build-fw v3ext $1"

        cd buildroot/build/output/*
        md5sum oi-* azbooka* > MD5SUMS
        sha1sum oi-* azbooka* > SHA1SUMS
        cd $WORKDIR
        cp -a buildroot/build/output ~

        cd

        sudo rm -rf "$WORKDIR"
}

WORKDIR=$(mktemp -d  $HOME/buildfw.XXXXXXXX)

: > report
build_all $1 > report 2>&1
mv report ~/output/
