#!/bin/sh
set -e

WORKDIR=$(mktemp -d  $HOME/buildfw.XXXXXXXX)

cd $WORKDIR

wget -c -t0 http://ftp.iplinux.org/contrib/iplinux-bootstrap/iplinux-bootstrap-LATEST.tar.bz2
tar xf iplinux-bootstrap-LATEST.tar.bz2
cd iplinux-bootstrap
./iplinux-bootstrap --debian-mirror=http://localhost:9999/debian/ ../buildroot
cd ..

sudo sh -c 'echo deb http://openinkpot.org/pub/oi/ asimov host/tools host/cross >> buildroot/etc/apt/sources.list'
wget -q -O- http://openinkpot.org/pub/gpgkey | buildroot/enter sh -c 'sudo apt-key add -'
buildroot/enter sh -c 'sudo apt-get update; sudo apt-get install --yes --force-yes oi-build-firmware'
buildroot/enter sh -c 'sudo apt-get --yes --force-yes dist-upgrade'

buildroot/enter sh -c 'build-fw --device=n516 --variant=azbooka'; killall ld-linux-x86-64
buildroot/enter sh -c 'build-fw --device=n516'; killall ld-linux-x86-64
buildroot/enter sh -c 'build-fw --device=v3'; killall ld-linux-x86-64
buildroot/enter sh -c 'build-fw --device=v3 --mode=live'; killall ld-linux-x86-64
buildroot/enter sh -c 'build-fw --device=v3 --mode=nfsroot'; killall ld-linux-x86-64
buildroot/enter sh -c 'build-fw --device=v3ext'; killall ld-linux-x86-64

cd buildroot/build/output/*/
md5sum oi-* azbooka* > MD5SUMS
sha1sum oi-* azbooka* > SHA1SUMS
cp -a buildroot/build/output ~


cd

sudo rm -rf "$WORKDIR"

