#!/bin/bash
set -e

WORKDIR=$(mktemp)
TARGETDIR=/srv/www/openinkpot.org/htdocs/pub/daily
SUBJECT="OI: Daily builds report"
RECIPIENT="dottedmag@dottedmag.net"

send_mail(){
	df -h >> $1
	/usr/bin/mail $SUBJECT $RECIPIENT < $1
}

rsync -ar 'ab:output/*/*' $WORKDIR
ssh ab rm -rf output

if [ -a ${WORKDIR}/report ]; then
	# if something was fetched at all
	if [ -s ${WORKDIR}/report ]; then
		#if there was no single build error
		rm -rf ${TARGETDIR}/*
		mv ${WORKDIR}/* $TARGETDIR
		echo "Files were moved to pub/daily" >> ${TARGETDIR}/report
	else
		#if there were errors
		echo "Some errors occured during building fw. Not swapping daily" >> ${TARGETDIR}/report
	fi
	send_mail ${TARGETDIR}/report
	rm -f ${TARGETDIR}/report
else
	# if fetching failed
	echo "Fetching build files failed!" > ${WORKDIR}/report
	send_mail ${WORKDIR}/report
fi

rm -rf "$WORKDIR"
