#!/bin/bash
set -e

WORKDIR=$(mktemp -d)
TARGETDIR=/srv/www/openinkpot.org/htdocs/pub/daily/
SUBJECT="OI: Daily builds report"
RECIPIENT="openinkpot-builds@openinkpot.org"

send_mail(){
	df -h >> ${WORKDIR}/report
	cat ${WORKDIR}/log >> ${WORKDIR}/report
	mail $SUBJECT $RECIPIENT < ${WORKDIR}/report
}

create_html(){
	cd $WORKDIR
cat <<EOF >index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> 
<html>
<head>
<title>OpenInkpot's daily builds</title>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
<style TYPE="text/css">
<!--
body {
font-family: sans-serif;
background: white;
color: #333 }

a {
color: blue;
text-decoration: none;
}

a:hover {
text-decoration: underline;
}

table#header {
width: 100%;
}

table#header td.logo {
width: 96px;
border: 0px;
}

table#header td.main {
font-size: 250%;
padding-left: 10px;
white-space: nowrap;
}

table#header td.sub {
color: #777;
border-top: solid 1px #ccc;
padding-left: 10px;
}

table.fw {
font-weight: normal;
font-size: 12px;
color: #fff;
border-collapse: collapse;
border-spacing: 10px;
}

table.fw td {
background-color: #fff;
color: #000;
padding: 4px;
text-align: left;
border: 1px solid #fff;
border-bottom: 1px solid #bbb;
}

table.fw th {
background-color: #9e1b3c;
border: 2px solid white;
}

table.fw tr:hover td {
color: blue;
}

img {
border: 0px;
}

-->
</style>
</head>
<table id='header'> 
<tr><td class='logo' rowspan='2'><a href='http://openinkpot.org'><img src='http://openinkpot.org/chrome/logo-half-border.png' alt='OpenInkpot logo'></a></td><td class='main'>OpenInkpot's daily builds</td></tr> 
<tr><td class='sub'>your source of fresh firmware upgrades</td></tr></table>
EOF
	echo "<h2>Hanvon n516</h2>" >> index.html
	table_group oi-hanvon-n516
	echo "<h2>Hanlin v3/v3ext</h2>" >> index.html
	table_group oi-hanlin-v3
	echo "</html>" >> index.html
}

table_group(){
	echo "<table class='fw'>" >> index.html
	echo "<tr><th>name</th><th>size</th><th>md5</th><th>sha1</th></tr>" >> index.html
	table_rows $1
	if [ "$1" == "oi-hanvon-n516" ]; then
		echo "<tr><th colspan="4">Azbooka</th></tr>" >> index.html
		table_rows azbooka
	fi

	echo "</table>" >> index.html
}

table_rows() {
	for row in $(ls ${1}*.zip ${1}*.bz2); do
		echo -n "<tr><td><a href=\"${row}\">${row}</a></td><td>" >> index.html
		stat -c %s ${row} >> index.html
		echo -n "</td><td>" >> index.html
		grep $row MD5SUMS | cut -d ' ' -f 1 >> index.html
		echo -n "</td><td>" >> index.html
		grep $row SHA1SUMS | cut -d ' ' -f 1 >> index.html
		echo -n "</td></tr>" >> index.html
	done
}

rsync -ar 'ab:output/*/*' $WORKDIR
ssh ab rm -rf output

if [ -a ${WORKDIR}/report ]; then
	# if something was fetched at all
	if [ -s ${WORKDIR}/report ]; then
		#if there were errors
		echo "Some errors occured during building fw. Not swapping daily" >> ${WORKDIR}/report
	else
		#if there was no single build error
		create_html
		rm -f ${TARGETDIR}*
		mv ${WORKDIR}/*.zip ${WORKDIR}/*.bz2 ${WORKDIR}/index.html $TARGETDIR
		echo "Files were moved to pub/daily" >> ${WORKDIR}/report
	fi
	send_mail
else
	# if fetching failed
	echo "Fetching build files failed!" > ${WORKDIR}/report
	send_mail ${WORKDIR}/report
fi

rm -rf "$WORKDIR"
